all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-35-163-70-16.us-west-2.compute.amazonaws.com
        server-two:
          ansible_host: ec2-34-221-221-250.us-west-2.compute.amazonaws.com
